image:
  repository: ghcr.io/evgenz-mr/gitops-python-api
  tag: latest
containerPort: 8080
service:
  port: 8080
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 100
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop: ["ALL"]
probes:
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /health
    initialDelaySeconds: 3
    periodSeconds: 5
