apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: python-api-config
  namespace: gitops-demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: SecretStore
  target:
    name: python-api-config
    creationPolicy: Owner
  data:
    - secretKey: API_TOKEN
      remoteRef:
        key: gitops-demo/python-api
        property: api_token
