image:
  repository: ghcr.io/evgenz-mr/gitops-java-api
  tag: latest
containerPort: 8080
service:
  port: 8080
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 100
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop: ["ALL"]
probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 25
    periodSeconds: 10
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 10
    periodSeconds: 5
