apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: gitops-demo
spec:
  metrics:
    - name: success-rate
      interval: 30s
      count: 5
      successCondition: result[0] >= 0.95
      failureLimit: 2
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
          query: |
            1 - (
              sum(rate(http_requests_total{status=~"5..",service="python"}[2m]))
              /
              clamp_min(sum(rate(http_requests_total{service="python"}[2m])), 0.001)
            )
