apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-api
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: [gitops-demo]
  selector:
    matchLabels:
      app.kubernetes.io/name: python
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-api
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: [gitops-demo]
  selector:
    matchLabels:
      app.kubernetes.io/name: java
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
